name: Déploiement auto sur le serveur

on:
  push:
    branches:
      - master  # Déclenchement quand on pousse sur master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le repo
      uses: actions/checkout@v3

    - name: Déploiement sur le serveur
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2002  # à adapter si tu as modifié le port SSH
        script: |
          cd /home/mada-etech/Bureau/proj
          git pull origin master
          
    
